<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yang</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~@y</string>
	<key>name</key>
	<string>yang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>leaf keyword</string>
			<key>match</key>
			<string>(leaf) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.leaf.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>leaf-list keyword</string>
			<key>match</key>
			<string>(leaf-list) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.leaf-list.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>list keyword</string>
			<key>match</key>
			<string>(list) ([a-zA-Z0-9\-]+)</string>
			<key>name</key>
			<string>statement.list.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>key keyword</string>
			<key>match</key>
			<string>(key) ([a-zA-Z0-9\-]+)</string>
			<key>name</key>
			<string>statement.key.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>choice keyword</string>
			<key>match</key>
			<string>(choice) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.choice.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>container keyword</string>
			<key>match</key>
			<string>(container) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.container.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(grouping) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.grouping.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>uses keyword</string>
			<key>match</key>
			<string>(uses) ([a-zA-Z0-9\-_:]+)</string>
			<key>name</key>
			<string>statement.uses.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>type keyword</string>
			<key>match</key>
			<string>(type) ([a-zA-Z0-9;:\-_]+)</string>
			<key>name</key>
			<string>statement.type.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>mandatory keyword, tldr193</string>
			<key>match</key>
			<string>(mandatory) ([truefalse]+)</string>
			<key>name</key>
			<string>statement.manditory.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>key keyword, tldr193</string>
			<key>match</key>
			<string>(key) +([\"a-zA-Z0-9\-_: ;]+)</string>
			<key>name</key>
			<string>statement.key.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>enum keyword</string>
			<key>match</key>
			<string>(enum) +([\"a-zA-Z0-9\-_: ]+)</string>
			<key>name</key>
			<string>statement.type.enum.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(//.*$)</string>
			<key>name</key>
			<string>comment.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(module) +([a-zA-Z0-9;:\-_]+)</string>
			<key>name</key>
			<string>module.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(import) +([a-zA-Z0-9;:\-_]+)</string>
			<key>name</key>
			<string>import.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(prefix) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>import.prefix.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(revision) +([a-zA-Z0-9;:\-_]+)</string>
			<key>name</key>
			<string>revision.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(namespace)</string>
			<key>name</key>
			<string>namespace.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(prefix)</string>
			<key>name</key>
			<string>prefix.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(organization)</string>
			<key>name</key>
			<string>organization.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>grouping keyword</string>
			<key>match</key>
			<string>(contact)</string>
			<key>name</key>
			<string>contact.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>description keyword</string>
			<key>match</key>
			<string>(description)</string>
			<key>name</key>
			<string>description.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>typedef keyword</string>
			<key>match</key>
			<string>(typedef) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.typedef.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>pattern keyword</string>
			<key>match</key>
			<string>(pattern)</string>
			<key>name</key>
			<string>statement.pattern.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>augment keyword</string>
			<key>match</key>
			<string>(augment) ([\":/a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>statement.augment.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Identity keyword. tldr193</string>
			<key>match</key>
			<string>(identity) ([\":/a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>identity.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Identity keyword. tldr193</string>
			<key>match</key>
			<string>(base) ([\":/a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>identity.base.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Default keyword. tldr193</string>
			<key>match</key>
			<string>(default) ([\":/a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>default.yang</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([\"\'])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\"\'];)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.yang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>namespaced keyword</string>
			<key>match</key>
			<string>([a-zA-Z0-9\-_:]+) ([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>namespacedkeyword.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>other keyword</string>
			<key>match</key>
			<string>([a-zA-Z0-9\-_]+):([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>other.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>standalone keyword</string>
			<key>match</key>
			<string>([a-zA-Z0-9\-_]+)</string>
			<key>name</key>
			<string>standalone.yang</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>yang.plist</string>
	<key>uuid</key>
	<string>841B57AC-D241-4DBB-8766-BE2C4296C582</string>
</dict>
</plist>
